{"error code":"Server Error","url":"Ocured an error in path /users/5a7a7198-50d6-46c8-b163-4b9c508f54a8","message":"Todos is not defined","stack":"ReferenceError: Todos is not defined\n    at Object.updateUserData (E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\boards\\board.db.repository.js:48:24)\n    at Object.updateUserData (E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\boards\\board.service.js:38:60)\n    at E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\users\\user.router.js:95:25\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-02 16:23:58"}
{"error code":"Server Error","url":"Ocured an error in path /boards/f3c2fbed-de9e-4e2b-aa52-707fee1e8b85","message":"user is not defined","stack":"ReferenceError: user is not defined\n    at Object.updateBoardOnUser (E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\users\\user.db.repository.js:75:13)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\boards\\board.router.js:45:20\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-02 16:50:01"}
{"error code":"Server Error","url":"Ocured an error in path /boards/f3c2fbed-de9e-4e2b-aa52-707fee1e8b85","message":"updatedUser is not defined","stack":"ReferenceError: updatedUser is not defined\n    at Object.updateBoardOnUser (E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\users\\user.db.repository.js:88:3)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\boards\\board.router.js:45:20\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-02 16:50:18"}
{"error code":"Forbidden","url":"Ocured an error in path /users","message":"\"User already exist\"","stack":"ForbittenError: User already exist\n    at registerUser (E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\login\\login.service.js:32:11)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\users\\user.router.js:82:27\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-02 17:09:23"}
{"error code":"Conflict","url":"Ocured an error in path /users","message":"\"User with login dfgdfdfg@dfsdf.fgghgf already exist\"","stack":"ConflictError: User with login dfgdfdfg@dfsdf.fgghgf already exist\n    at registerUser (E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\login\\login.service.js:33:11)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\users\\user.router.js:82:27\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-02 17:11:37"}
{"error code":"Conflict","url":"Ocured an error in path /users","message":"\"User with login dfgdfdfg@dfsdf.fgghgf already exist\"","stack":"ConflictError: User with login dfgdfdfg@dfsdf.fgghgf already exist\n    at registerUser (E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\login\\login.service.js:33:11)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\users\\user.router.js:79:27\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-02 17:21:50"}
{"error code":"Server Error","url":"Ocured an error in path /users/026de483-58ff-48f5-930b-041722d59bae","message":"usersService is not defined","stack":"ReferenceError: usersService is not defined\n    at Object.updateUser (E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\users\\user.db.repository.js:30:26)\n    at Object.updateUser (E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\users\\user.service.js:23:45)\n    at E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\users\\user.router.js:90:37\n    at E:\\masha\\rss2020\\rsclone\\server\\src\\errors\\catchError.js:3:18\n    at Layer.handle [as handle_request] (E:\\masha\\rss2020\\rsclone\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\masha\\rss2020\\rsclone\\server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at E:\\masha\\rss2020\\rsclone\\server\\src\\validator\\validator.js:25:19\n    at E:\\masha\\rss2020\\rsclone\\server\\src\\errors\\catchError.js:3:18\n    at Layer.handle [as handle_request] (E:\\masha\\rss2020\\rsclone\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\masha\\rss2020\\rsclone\\server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (E:\\masha\\rss2020\\rsclone\\server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (E:\\masha\\rss2020\\rsclone\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at E:\\masha\\rss2020\\rsclone\\server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at param (E:\\masha\\rss2020\\rsclone\\server\\node_modules\\express\\lib\\router\\index.js:354:14)\n    at param (E:\\masha\\rss2020\\rsclone\\server\\node_modules\\express\\lib\\router\\index.js:365:14)\n    at Function.process_params (E:\\masha\\rss2020\\rsclone\\server\\node_modules\\express\\lib\\router\\index.js:410:3)","level":"error","timestamp":"2021-02-02 17:22:33"}
{"error code":"Server Error","url":"Ocured an error in path /users/026de483-58ff-48f5-930b-041722d59bae","message":"login is not defined","stack":"ReferenceError: login is not defined\n    at Object.updateUser (E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\users\\user.db.repository.js:31:50)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\users\\user.router.js:90:18\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-02 17:23:06"}
{"error code":"Conflict","url":"Ocured an error in path /users/026de483-58ff-48f5-930b-041722d59bae","message":"\"User with login dfgdfdfg@dfsdf.fgghgf already exist\"","stack":"ConflictError: User with login dfgdfdfg@dfsdf.fgghgf already exist\n    at Object.updateUser (E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\users\\user.db.repository.js:32:13)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\users\\user.router.js:90:18\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-02 17:23:43"}
{"error code":"Server Error","url":"Ocured an error in path /users/5a7a7198-50d6-46c8-b163-4b9c508f54a8","message":"Cannot read property 'columnId' of null","stack":"TypeError: Cannot read property 'columnId' of null\n    at Object.updateUserData (E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\tasks\\task.service.js:54:54)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\users\\user.router.js:92:5\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-02 17:24:30"}
{"error code":"Server Error","url":"Ocured an error in path /users/5a7a7198-50d6-46c8-b163-4b9c508f54a8","message":"Cannot read property 'columnId' of null","stack":"TypeError: Cannot read property 'columnId' of null\n    at Object.updateUserData (E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\tasks\\task.service.js:54:54)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\users\\user.router.js:92:15\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-02 17:26:41"}
{"error code":"Conflict","url":"Ocured an error in path /users/5a7a7198-50d6-46c8-b163-4b9c508f54a8","message":"\"User with login 1234 already exist\"","stack":"ConflictError: User with login 1234 already exist\n    at Object.updateUser (E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\users\\user.db.repository.js:32:13)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\users\\user.router.js:90:18\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-02 17:26:52"}
{"error code":"Server Error","url":"Ocured an error in path /users/5a7a7198-50d6-46c8-b163-4b9c508f54a8","message":"Cannot read property 'columnId' of null","stack":"TypeError: Cannot read property 'columnId' of null\n    at Object.updateUserData (E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\tasks\\task.service.js:54:54)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\users\\user.router.js:92:15\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-02 17:26:59"}
{"error code":"Server Error","url":"Ocured an error in path /users/5a7a7198-50d6-46c8-b163-4b9c508f54a8","message":"Cannot read property 'columnId' of null","stack":"TypeError: Cannot read property 'columnId' of null\n    at Object.updateUserData (E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\tasks\\task.service.js:55:54)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\users\\user.router.js:92:15\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-02 17:27:55"}
{"error code":"Server Error","url":"Ocured an error in path /e431dc9f-4a69-46ac-bd7e-d55344bd19b3/tasks/bebd2984-f433-4a69-ac49-799787f1f283/tags","message":"taskService.addTagToTask is not a function","stack":"TypeError: taskService.addTagToTask is not a function\n    at E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\tags\\tags.router.js:23:23\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-03 14:00:11"}
{"error code":"Server Error","url":"Ocured an error in path /e431dc9f-4a69-46ac-bd7e-d55344bd19b3/tasks/bebd2984-f433-4a69-ac49-799787f1f283/tags","message":"taskService.addTagToTask is not a function","stack":"TypeError: taskService.addTagToTask is not a function\n    at E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\tags\\tags.router.js:24:23\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-03 14:03:41"}
{"error code":"Not Found","url":"Ocured an error in path /boards/f3c2fbed-de9e-4e2b-aa52-707fee1e8b85","message":"\"Board with id f3c2fbed-de9e-4e2b-aa52-707fee1e8b85 not found\"","stack":"NotFoundError: Board with id f3c2fbed-de9e-4e2b-aa52-707fee1e8b85 not found\n    at getBoardById (E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\boards\\board.db.repository.js:13:11)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Object.getAllBoardData (E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\boards\\board.db.repository.js:19:21)\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\boards\\board.router.js:21:19\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-03 14:26:03"}
{"error code":"Not Found","url":"Ocured an error in path /users/93100d71-4b15-4630-a522-c3fbc3de15ec/addtoboard","message":"\"User with id 93100d71-4b15-4630-a522-c3fbc3de15ec not found\"","stack":"NotFoundError: User with id 93100d71-4b15-4630-a522-c3fbc3de15ec not found\n    at Object.getUserById (E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\users\\user.db.repository.js:13:11)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\resources\\users\\user.router.js:31:18\n    at async E:\\masha\\rss2020\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-03 15:18:23"}
